# /etc/X11/xorg.conf.d
# install: libinput, xf86-input-libinput
#
# see: https://www.mankier.com/4/libinput#Supported_Properties
# see: https://man.archlinux.org/man/libinput.4

############
# TOUCHPAD #
############

Section "InputClass"
    #Identifier "touchpad"
    Identifier "libinput touchpad catchall"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput" # based on `Driver` put configs in `libinput`, `synaptics` or alone.
    MatchIsTouchpad "1"
    
    Option "Tapping" 			"1"
    Option "AccelProfile" 		"adaptive" # adaptive, flat, custom
    Option "AccelSpeed" 		"0.183999" # -1 to 1
    Option "TappingButtonMap" 		"lrm" #1,2,3-finger taps
    Option "DisableWhileTyping" 	"1"
    Option "MiddleEmulation" 		"0"
    Option "NaturalScrolling" 		"1"
    Option "ScrollMethod" 		"twofinger" # none, twofinger, edge, button
    Option "ScrollPixelDistance" 	"7"
    Option "TappingDrag" 		"1"
    Option "ClickMethod" 		"clickfinger" # none, buttonareas, clickfinger
EndSection

############
# KEYBOARD #
############

Section "InputClass"
        Identifier "system-keyboard"
    	Driver "libinput"
        MatchIsKeyboard "on"
        
	Option "XkbLayout"	"us,ara"
        Option "XkbModel" 	"acer_laptop"
        Option "XkbVariant" 	","
        #Option "XkbOptions" 	"grp:win_space_toggle" toggle layout with: win+space
        Option "XkbOptions" 	"grp:alt_shift_toggle" # toggle layout with: alt+shift
        Option "AutoRepeat" 	"200 55"
EndSection

