# /etc/X11/xorg.conf.d
# install: libinput, xf86-input-libinput

############
# TOUCHPAD #
############

Section "InputClass"
    Identifier "touchpad"
    Driver "libinput" # based on `Driver` put configs in `libinput`, `synaptics` or alone.
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "AccelProfile" "adaptive" # adaptive, flat, custom
    Option "AccelSpeed" "0.5" # -1 to 1
    Option "TappingButtonMap" "lrm" #1,2,3-finger taps
    Option "DisableWhileTyping" "on"
    Option "MiddleEmulation" "off"
    Option "NaturalScrolling" "on"
    Option "ScrollMethod" "twofinger"
    Option "ScrollPixelDistance" "7"
    Option "TappingDrag" "on"
    Option "ClickMethod" "clickfinger"
EndSection

############
# KEYBOARD #
############

Section "InputClass"
        Identifier "system-keyboard"
    	Driver "libinput"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ara"
        Option "XkbModel" "acer_laptop"
        Option "XkbVariant" ","
        #Option "XkbOptions" "grp:win_space_toggle" toggle layout with: win+space
        Option "XkbOptions" "grp:alt_shift_toggle" # toggle layout with: alt+shift
        Option "AutoRepeat" "200 55"
EndSection

