[window]
dimensions      = { columns = 88, lines = 27 }
dynamic_padding = true
opacity         = 0.95
#startup_mode   = "Windowed"
title           = "Alacritty"
dynamic_title   = false

[scrolling]
history    = 1000
multiplier = 1

[font]
size = 9.2 #7.8, [9.2, ...]
#normal = { family = "CaskaydiaMono NFM",            style = "Regular" }
#normal = { family = "CaskaydiaMono Nerd Font Mono", style = "SemiLight" }
#normal = { family = "NotoSansM Nerd Font Mono", style = "Regular" }
#normal = { family = "LiterationMono Nerd Font Mono", style = "Regular" }
#normal = { family = "Hack Nerd Font Mono", style = "Regular" }
#normal      = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
#normal      = { family = "MesloLGSDZ Nerd Font Mono", style = "Regular" }
#normal      = { family = "JetBrainsMono NFM", style = "Regular" }
#normal      = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
#normal      = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
#normal      = { family = "SauceCodePro NFM", style = "Regular" }
#normal      = { family = "SauceCodePro NFM", style = "Medium" }
#normal      = { family = "SauceCodePro NFM", style = "SemiBold" }
#normal      = { family = "Maple Mono NF", style = "Regular" }
#normal      = { family = "Maple Mono NL NF", style = "Regular" }
#normal      = { family = "FiraCode Nerd Font Mono", style = "Regular" }
#normal      = { family = "FiraCode Nerd Font Mono", style = "Retina" }
normal      = { family = "MesloLGSDZ Nerd Font Mono", style = "Regular" }
italic      = { family = "MesloLGSDZ Nerd Font Mono", style = "Italic" }
bold        = { family = "MesloLGSDZ Nerd Font Mono", style = "Bold" }
bold_italic = { family = "MesloLGSDZ Nerd Font Mono", style = "Bold Italic" }

[colors]	
cursor    = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "CellBackground", background = "CellForeground" }
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#dddddd"
background = "#090909"
#dim_foreground    = "#828482"
#bright_foreground = "None"

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }
blink_timeout    = 10
unfocused_hollow = true #when true cursor will be rendered as a hollow box when the window is not focused

[mouse]
hide_when_typing = true
bindings = [
	{ mouse = "Right", mods = "Control", action = "Paste" },
	{ mouse = "Right", action = "Copy" },
]

[keyboard]
bindings = [
	{ key = "c", mods = "Control | Shift", action = "Copy" },
	{ key = "v", mods = "Control | Shift", action = "Paste" },
	{ key = "+", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "0", mods = "Control", action = "ResetFontSize" },
    { key = "Numpad0", mods = "Control", action = "ResetFontSize" },
	#{ key = "t", mods = "Control | Shift", action = "SpawnNewInstance" },
	#{ key = "c", mods = "Super | Shift", action = "Quit" },
	{ key = "PageUp", action = "ScrollHalfPageDown" },
	{ key = "PageDown", action = "ScrollHalfPageUp" },
	{ key = "Return", mods = "Super | Shift", command = "alacritty" },
]

[bell]
animation = "Ease"
duration  = 0
color = "#777777"
#command = { program = "echo", args = ["WRONG",] }
